#!/bin/sh

# -------------------------------------------------------------------------- #
# Copyright 2010-2016, OpenNebula Systems                                    #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

CONFIG_CONTEXT="/etc/one-context.sh"

export_rc_vars() {
    if [ -f $1 ] ; then
        ONE_VARS=`cat $1 | egrep -e '^[a-zA-Z\-\_0-9]*=' | sed 's/=.*$//'`

        . $1

        for v in $ONE_VARS; do
            export $v
        done
    fi
}

execute_scripts() {
    SCRIPTS_DIR="/etc/one-context.d"
    for script in $SCRIPTS_DIR/*; do
        sh -x "$script" "$1"
    done
}

start() {
    CONTEXT_DEV="/dev/sr0"
    VOLNAME="$(volname $CONTEXT_DEV)"

    if [ -e "$CONFIG_CONTEXT" ]; then
        export_rc_vars "$CONFIG_CONTEXT"
        cp "$CONFIG_CONTEXT" /tmp/context.sh

        execute_scripts "$1"
    elif [ -n "$VOLNAME" ]; then
        mount -t iso9660 -o ro $CONTEXT_DEV /mnt
        if [ -f /mnt/context.sh ]; then
            export_rc_vars /mnt/context.sh
            cp /mnt/context.sh /tmp/context.sh
        fi

        execute_scripts "$1"

        umount /mnt
    elif type vmtoolsd ; then
        vmtoolsd --cmd 'info-get guestinfo.opennebula.context' | \
            base64 -d > /tmp/context.sh
        export_rc_vars /tmp/context.sh
        execute_scripts "$1"
    fi
}

COMMAND="$1"

if [ "$COMMAND" == "reconfigure" ]; then
    cat > "$CONFIG_CONTEXT"

    COMMAND="reload"
fi

echo 2000 > /sys/module/block/parameters/events_dfl_poll_msecs

start "$COMMAND"
